// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");

function $less$less(f, g, x) {
  return Curry._1(f, Curry._1(g, x));
}

function $great$great(f, g, x) {
  return Curry._1(g, Curry._1(f, x));
}

function $$const(x, param) {
  return x;
}

function identity(x) {
  return x;
}

function ok(x) {
  return /* Ok */Block.__(0, [x]);
}

function error(e) {
  return /* Error */Block.__(1, [e]);
}

var Result = 0;

var unit = /* () */0;

exports.Result = Result;
exports.$less$less = $less$less;
exports.$great$great = $great$great;
exports.$$const = $$const;
exports.identity = identity;
exports.unit = unit;
exports.ok = ok;
exports.error = error;
/* No side effect */
